"""empty message

Revision ID: 40525f200a8a
Revises: 61c74d0c73a3
Create Date: 2025-07-28 12:33:07.151707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40525f200a8a'
down_revision = '61c74d0c73a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
